spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      names: ${job.name:NONE}

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
